export type PingData = {
   ping: string
}

export const OFFER_STATE = {
	CREATED: 'CREATED',
	INVOICE_PAID: 'INVOICE_PAID',
	CLAIMED: 'CLAIMED',
	EXPIRED: 'EXPIRED',
	CANCELLED: 'CANCELLED',
	COMPLETED: 'COMPLETED',
	RECEIPT_SUBMITTED: 'RECEIPT_SUBMITTED',
	MARKED_WITH_ISSUE: 'MARKED_WITH_ISSUE',
	
};


